### ISSUE TITLE
When will air2 be updated?

### ISSUE THREAD

**Issue by raydoomed** [wheaney/xrealAirLinuxDriver#25]
Looking forward to it thank you

**Comment by wheaney** [comment]
Hi, I'm not sure exactly what you mean. If you're asking if the driver will work with the Air 2/pro devices, my assumption would be "yes," at least for air 2s since I don't believe the underlying hardware is changing at all (i.e. the changes are purely aesthetic). For the pros, I don't know exactly and I can't find the Reddit post I saw that breaks down how/if the hardware is changing. My hope is that no work is needed, but I'm certainly open to accommodating the new hardware. 

I'm going to close out this issue, and we can open another if someone tests with the new hardware and finds it doesn't work.
